import type { DifficultyId } from '../models.js';
import { PLAYER_TARGET_SCORE_BY_DIFFICULTY } from '../config/difficultyTargets.js';
import type { DifficultyProfile } from './types.js';

const DIFFICULTY_PROFILES: Record<DifficultyId, DifficultyProfile> = {
  warmup: {
    id: 'warmup',
    label: '热身局',
    playerTargetScore: PLAYER_TARGET_SCORE_BY_DIFFICULTY.warmup,
    caseCount: 3,
    maxDayRange: { min: 25, max: 26 },
    startDayRange: { min: 5, max: 18 },
    startMonthPool: [4, 5, 9],
    windowDaysRange: { min: 10, max: 16 },
    initialTrustRange: { min: 62, max: 74 },
    initialPatienceRange: { min: 54, max: 78 },
    initialHeatRange: { min: 56, max: 72 },
    initialUrgencyRange: { min: 44, max: 68 },
    scriptedEventCountRange: { min: 2, max: 2 },
    competitionGroupCountRange: { min: 1, max: 1 },
    randomEventWeights: {
      'school-boom': 5,
      'policy-shift': 1,
      'competitor-cut': 1,
    },
    ruleAdjustments: {
      maxDay: 26,
      initialCash: 24,
      initialReputation: 61,
      randomEventProbability: 0.09,
      dailyMarketEventProbability: 0.1,
      rivalListingSpawnChance: 0.04,
      rivalPressureHeatImpact: 0.7,
      rivalPressureTrustImpact: 0.25,
      companySharedLeadPressureBase: 18,
      companyReferralChanceBase: 0.14,
      rivalLossProbabilityScale: 0.08,
    },
    generationDifficultyBand: { min: 3, max: 8 },
  },
  easy: {
    id: 'easy',
    label: '入门局',
    playerTargetScore: PLAYER_TARGET_SCORE_BY_DIFFICULTY.easy,
    caseCount: 4,
    maxDayRange: { min: 23, max: 24 },
    startDayRange: { min: 5, max: 18 },
    startMonthPool: [5, 9, 10],
    windowDaysRange: { min: 8, max: 14 },
    initialTrustRange: { min: 58, max: 70 },
    initialPatienceRange: { min: 46, max: 74 },
    initialHeatRange: { min: 54, max: 70 },
    initialUrgencyRange: { min: 48, max: 74 },
    scriptedEventCountRange: { min: 2, max: 2 },
    competitionGroupCountRange: { min: 1, max: 2 },
    randomEventWeights: {
      'school-boom': 4,
      'policy-shift': 2,
      'competitor-cut': 2,
    },
    ruleAdjustments: {
      maxDay: 24,
      initialCash: 22,
      initialReputation: 59,
      randomEventProbability: 0.11,
      dailyMarketEventProbability: 0.16,
      rivalListingSpawnChance: 0.05,
      rivalPressureHeatImpact: 0.75,
      rivalPressureTrustImpact: 0.22,
      companySharedLeadPressureBase: 24,
      companyReferralChanceBase: 0.12,
      rivalLossProbabilityScale: 0.1,
    },
    generationDifficultyBand: { min: 10, max: 26 },
  },
  standard: {
    id: 'standard',
    label: '标准局',
    playerTargetScore: PLAYER_TARGET_SCORE_BY_DIFFICULTY.standard,
    caseCount: 5,
    maxDayRange: { min: 20, max: 21 },
    startDayRange: { min: 3, max: 16 },
    startMonthPool: [3, 6, 11],
    windowDaysRange: { min: 7, max: 12 },
    initialTrustRange: { min: 54, max: 66 },
    initialPatienceRange: { min: 40, max: 68 },
    initialHeatRange: { min: 52, max: 68 },
    initialUrgencyRange: { min: 55, max: 80 },
    scriptedEventCountRange: { min: 2, max: 3 },
    competitionGroupCountRange: { min: 2, max: 3 },
    randomEventWeights: {
      'school-boom': 2,
      'policy-shift': 3,
      'competitor-cut': 4,
    },
    ruleAdjustments: {
      maxDay: 21,
      initialCash: 18,
      initialReputation: 55,
      randomEventProbability: 0.16,
      dailyMarketEventProbability: 0.24,
      rivalListingSpawnChance: 0.1,
      rivalPressureHeatImpact: 1.1,
      rivalPressureTrustImpact: 0.42,
      companySharedLeadPressureBase: 36,
      companyReferralChanceBase: 0.09,
      rivalLossProbabilityScale: 0.22,
    },
    generationDifficultyBand: { min: 18, max: 34 },
  },
  advanced: {
    id: 'advanced',
    label: '进阶局',
    playerTargetScore: PLAYER_TARGET_SCORE_BY_DIFFICULTY.advanced,
    caseCount: 5,
    maxDayRange: { min: 19, max: 20 },
    startDayRange: { min: 2, max: 18 },
    startMonthPool: [3, 6, 10],
    windowDaysRange: { min: 6, max: 10 },
    initialTrustRange: { min: 51, max: 63 },
    initialPatienceRange: { min: 36, max: 60 },
    initialHeatRange: { min: 48, max: 66 },
    initialUrgencyRange: { min: 60, max: 84 },
    scriptedEventCountRange: { min: 3, max: 3 },
    competitionGroupCountRange: { min: 2, max: 3 },
    randomEventWeights: {
      'school-boom': 2,
      'policy-shift': 4,
      'competitor-cut': 5,
    },
    ruleAdjustments: {
      maxDay: 20,
      initialCash: 17,
      initialReputation: 54,
      randomEventProbability: 0.18,
      competitionPressureThreshold: 68,
      dailyMarketEventProbability: 0.28,
      rivalListingSpawnChance: 0.2,
      rivalPressureHeatImpact: 1.9,
      rivalPressureTrustImpact: 0.9,
      companySharedLeadPressureBase: 44,
      companyReferralChanceBase: 0.08,
      rivalLossProbabilityScale: 0.48,
    },
    generationDifficultyBand: { min: 28, max: 42 },
  },
  hard: {
    id: 'hard',
    label: '高压局',
    playerTargetScore: PLAYER_TARGET_SCORE_BY_DIFFICULTY.hard,
    caseCount: 6,
    maxDayRange: { min: 17, max: 18 },
    startDayRange: { min: 2, max: 18 },
    startMonthPool: [2, 8, 12],
    windowDaysRange: { min: 5, max: 8 },
    initialTrustRange: { min: 49, max: 61 },
    initialPatienceRange: { min: 32, max: 58 },
    initialHeatRange: { min: 48, max: 67 },
    initialUrgencyRange: { min: 56, max: 88 },
    scriptedEventCountRange: { min: 2, max: 3 },
    competitionGroupCountRange: { min: 2, max: 3 },
    randomEventWeights: {
      'school-boom': 1,
      'policy-shift': 4,
      'competitor-cut': 6,
    },
    ruleAdjustments: {
      maxDay: 18,
      initialCash: 16,
      initialReputation: 52,
      randomEventProbability: 0.21,
      competitionPressureThreshold: 67,
      competitionHeatPenaltyMin: 3,
      competitionHeatPenaltyMax: 6,
      dailyMarketEventProbability: 0.32,
      rivalListingSpawnChance: 0.26,
      rivalPressureHeatImpact: 2.2,
      rivalPressureTrustImpact: 1.1,
      companySharedLeadPressureBase: 52,
      companyReferralChanceBase: 0.06,
      rivalLossProbabilityScale: 0.72,
    },
    generationDifficultyBand: { min: 38, max: 58 },
  },
  extreme: {
    id: 'extreme',
    label: '极限局',
    playerTargetScore: PLAYER_TARGET_SCORE_BY_DIFFICULTY.extreme,
    caseCount: 6,
    maxDayRange: { min: 16, max: 17 },
    startDayRange: { min: 2, max: 20 },
    startMonthPool: [1, 2, 12],
    windowDaysRange: { min: 4, max: 7 },
    initialTrustRange: { min: 46, max: 58 },
    initialPatienceRange: { min: 28, max: 48 },
    initialHeatRange: { min: 45, max: 64 },
    initialUrgencyRange: { min: 68, max: 90 },
    scriptedEventCountRange: { min: 3, max: 3 },
    competitionGroupCountRange: { min: 2, max: 3 },
    randomEventWeights: {
      'school-boom': 1,
      'policy-shift': 5,
      'competitor-cut': 7,
    },
    ruleAdjustments: {
      maxDay: 17,
      initialCash: 14,
      initialReputation: 50,
      randomEventProbability: 0.24,
      competitionPressureThreshold: 65,
      competitionHeatPenaltyMin: 4,
      competitionHeatPenaltyMax: 7,
      ownerUntouchedTrustLoss: 2,
      urgentOwnerUntouchedTrustLoss: 4,
      dailyMarketEventProbability: 0.38,
      rivalListingSpawnChance: 0.32,
      rivalPressureHeatImpact: 2.6,
      rivalPressureTrustImpact: 1.3,
      companySharedLeadPressureBase: 60,
      companyReferralChanceBase: 0.05,
      rivalLossProbabilityScale: 0.9,
    },
    generationDifficultyBand: { min: 46, max: 68 },
  },
};

export function listDifficultyProfiles() {
  return Object.values(DIFFICULTY_PROFILES).map((profile) => structuredClone(profile));
}

export function getDifficultyProfile(difficultyId: DifficultyId) {
  return structuredClone(DIFFICULTY_PROFILES[difficultyId]);
}
