import type { WorldSpec } from '../models.js';

export const BUILT_IN_WORLD: WorldSpec = {
  id: 'shanghai-resale-2026',
  version: 1,
  name: '上海二手房经营世界',
  marketCells: [
    {
      id: 'mc-qiantan',
      name: '浦东前滩 | 80-90㎡ 刚改',
      demandHeat: 76,
      supplyPressure: 62,
      competitivePressure: 58,
      sentiment: 68,
      monthlyFactors: [-8, -5, 2, 5, 6, 4, 1, -2, 7, 9, 3, -4],
    },
    {
      id: 'mc-jingan',
      name: '静安寺北 | 60-75㎡ 资产型',
      demandHeat: 81,
      supplyPressure: 54,
      competitivePressure: 51,
      sentiment: 71,
      monthlyFactors: [-6, -4, 3, 4, 5, 2, 1, -1, 6, 8, 2, -3],
    },
  ],
  channels: [
    { id: 'xiaohongshu', name: '小红书推广', quality: 0.56, controllability: 0.48, leadSource: 'direct' },
    { id: 'broker-network', name: '经纪人投放', quality: 0.67, controllability: 0.36, leadSource: 'broker' },
    { id: 'open-day', name: '开放日', quality: 0.74, controllability: 0.76, leadSource: 'direct' },
    { id: 'private-referral', name: '私域转介绍', quality: 0.72, controllability: 0.72, leadSource: 'direct' },
  ],
  customers: [
    { id: 'cus-01', name: '林家改善客', profile: '孩子今年入学，决策速度快', budgetMin: 780, budgetMax: 860, targetDistrict: '浦东前滩', layouts: ['2室2厅1卫', '3室2厅2卫'], activity: 82, urgency: 78, priceSensitivity: 68, preferences: ['地铁近', '学区', '采光好'] },
    { id: 'cus-02', name: '陈先生新婚客', profile: '两个月内想落定婚房', budgetMin: 590, budgetMax: 660, targetDistrict: '静安寺北', layouts: ['1室1厅1卫', '2室2厅1卫'], activity: 79, urgency: 86, priceSensitivity: 72, preferences: ['地段强', '出租回报'] },
    { id: 'cus-03', name: '冯女士改善客', profile: '想在暑假前完成置换', budgetMin: 880, budgetMax: 980, targetDistrict: '浦东前滩', layouts: ['3室2厅2卫'], activity: 74, urgency: 72, priceSensitivity: 58, preferences: ['改善', '采光好', '车位'] },
    { id: 'cus-04', name: '孙先生学区客', profile: '对学区敏感，愿意多看几套', budgetMin: 760, budgetMax: 820, targetDistrict: '浦东前滩', layouts: ['2室2厅1卫'], activity: 56, urgency: 69, priceSensitivity: 74, preferences: ['学区', '采光好'] },
    { id: 'cus-05', name: '方女士投资客', profile: '追求出租回报和总价控制', budgetMin: 610, budgetMax: 690, targetDistrict: '静安寺北', layouts: ['1室1厅1卫'], activity: 61, urgency: 52, priceSensitivity: 65, preferences: ['出租回报', '地段强'] },
    { id: 'cus-06', name: '高女士首置客', profile: '需要更容易成交的两房盘', budgetMin: 780, budgetMax: 835, targetDistrict: '浦东前滩', layouts: ['2室2厅1卫'], activity: 76, urgency: 67, priceSensitivity: 78, preferences: ['地铁近', '采光好'] },
    { id: 'cus-07', name: '许先生资产客', profile: '重视地段和转手效率', budgetMin: 600, budgetMax: 650, targetDistrict: '静安寺北', layouts: ['1室1厅1卫'], activity: 66, urgency: 73, priceSensitivity: 55, preferences: ['地段强', '总价友好'] },
    { id: 'cus-08', name: '董先生换房客', profile: '持币等议价窗口', budgetMin: 900, budgetMax: 980, targetDistrict: '静安寺北', layouts: ['2室2厅1卫', '3室2厅2卫'], activity: 63, urgency: 58, priceSensitivity: 49, preferences: ['地段强', '改善'] },
  ],
  ownerArchetypes: [
    {
      id: 'anxious',
      label: '焦虑型',
      description: '窗口感强，愿意为了速度做更明显的价格动作。',
      trustDecayMultiplier: 1.4,
      priceElasticity: 1.25,
      urgencyGrowthBonus: 2,
      heatSensitivity: 0.9,
      patienceDelta: -2,
      preferredTactic: 'deep-cut',
    },
    {
      id: 'fair-value',
      label: '等价型',
      description: '强调合理价值，对无依据的压价更敏感。',
      trustDecayMultiplier: 0.9,
      priceElasticity: 0.7,
      urgencyGrowthBonus: 0,
      heatSensitivity: 0.6,
      patienceDelta: 1,
      preferredTactic: 'hold-story',
    },
    {
      id: 'trial-balloon',
      label: '试水型',
      description: '试水心态强，窗口短，撤盘倾向高。',
      trustDecayMultiplier: 1.15,
      priceElasticity: 0.95,
      urgencyGrowthBonus: 1,
      heatSensitivity: 1.1,
      patienceDelta: -3,
      preferredTactic: 'small-cut',
    },
    {
      id: 'game-player',
      label: '博弈型',
      description: '喜欢试探市场，对竞品和政策信息极其敏感。',
      trustDecayMultiplier: 1.05,
      priceElasticity: 0.85,
      urgencyGrowthBonus: 1,
      heatSensitivity: 1.2,
      patienceDelta: 0,
      preferredTactic: 'hold-story',
    },
  ],
  housePrototypes: [
    {
      id: 'proto-ruiheli-89',
      title: '瑞和里 89㎡ 两房',
      community: '瑞和里',
      district: '浦东前滩',
      layout: '2室2厅1卫',
      area: 89,
      marketCellId: 'mc-qiantan',
      marketPrice: 802,
      bottomPrice: 785,
      story: '高确定性学区刚改叙事',
      tags: ['学区', '地铁近', '采光好'],
      defects: ['报价偏硬', '次卧偏小'],
      axisScores: { layout: 70, light: 85, floor: 60, decor: 50, amenity: 65, neighborhood: 80, structure: 75 },
    },
    {
      id: 'proto-xinghuyuan-92',
      title: '星湖苑 92㎡ 两房',
      community: '星湖苑',
      district: '浦东前滩',
      layout: '2室2厅1卫',
      area: 92,
      marketCellId: 'mc-qiantan',
      marketPrice: 836,
      bottomPrice: 808,
      story: '改善家庭稳定交付感',
      tags: ['改善', '车位', '采光好'],
      defects: ['总价高'],
      axisScores: { layout: 76, light: 80, floor: 73, decor: 64, amenity: 78, neighborhood: 84, structure: 77 },
    },
    {
      id: 'proto-jiangyuefu-128',
      title: '江悦府 128㎡ 三房',
      community: '江悦府',
      district: '浦东前滩',
      layout: '3室2厅2卫',
      area: 128,
      marketCellId: 'mc-qiantan',
      marketPrice: 1260,
      bottomPrice: 1208,
      story: '改善家庭稳定交付感',
      tags: ['改善', '江景', '车位'],
      defects: ['总价高', '竞品新'],
      axisScores: { layout: 82, light: 79, floor: 71, decor: 68, amenity: 83, neighborhood: 88, structure: 80 },
    },
    {
      id: 'proto-jiayue-71',
      title: '嘉樾公馆 71㎡ 一房',
      community: '嘉樾公馆',
      district: '静安寺北',
      layout: '1室1厅1卫',
      area: 71,
      marketCellId: 'mc-jingan',
      marketPrice: 645,
      bottomPrice: 590,
      story: '青年资产保值叙事',
      tags: ['总价友好', '地段强', '出租回报'],
      defects: ['朝向一般'],
      axisScores: { layout: 65, light: 50, floor: 90, decor: 85, amenity: 75, neighborhood: 95, structure: 60 },
    },
    {
      id: 'proto-jiali-east-118',
      title: '嘉里东院 118㎡ 三房',
      community: '嘉里东院',
      district: '静安寺北',
      layout: '3室2厅2卫',
      area: 118,
      marketCellId: 'mc-jingan',
      marketPrice: 1106,
      bottomPrice: 1048,
      story: '核心地段改善保值叙事',
      tags: ['地段强', '改善', '车位'],
      defects: ['得房率低'],
      axisScores: { layout: 78, light: 72, floor: 84, decor: 76, amenity: 88, neighborhood: 96, structure: 68 },
    },
    {
      id: 'proto-wanhang-63',
      title: '万航小区 63㎡ 一房',
      community: '万航小区',
      district: '静安寺北',
      layout: '1室1厅1卫',
      area: 63,
      marketCellId: 'mc-jingan',
      marketPrice: 598,
      bottomPrice: 562,
      story: '地段强总价友好叙事',
      tags: ['总价友好', '地段强'],
      defects: ['邻近马路'],
      axisScores: { layout: 61, light: 58, floor: 66, decor: 54, amenity: 71, neighborhood: 90, structure: 62 },
    },
  ],
  randomEventTemplates: [
    { id: 'policy-shift', title: '政策利空', tone: 'danger', actor: '宏观' },
    { id: 'school-boom', title: '学区利好', tone: 'success', actor: '市场' },
    { id: 'competitor-cut', title: '竞对降价', tone: 'danger', actor: '市场竞争' },
  ],
  rivalStoreArchetypes: [
    {
      id: 'same-company-traffic',
      name: '同店流量组',
      type: 'same_company',
      style: 'traffic',
      districtFocus: ['浦东前滩', '静安寺北'],
      leadCapturePower: 48,
      sellerInfluencePower: 34,
      pricingPressurePower: 30,
    },
    {
      id: 'external-aggressive',
      name: '外部门店急售组',
      type: 'external_company',
      style: 'aggressive',
      districtFocus: ['浦东前滩'],
      leadCapturePower: 62,
      sellerInfluencePower: 56,
      pricingPressurePower: 68,
    },
    {
      id: 'external-relationship',
      name: '外部熟人盘门店',
      type: 'external_company',
      style: 'relationship',
      districtFocus: ['静安寺北'],
      leadCapturePower: 42,
      sellerInfluencePower: 68,
      pricingPressurePower: 44,
    },
  ],
  rivalListingArchetypes: [
    {
      id: 'urgent-cut',
      titlePrefix: '急售平替盘',
      segment: '急售',
      sourceBias: 'external_company',
      baseHeat: 68,
      freshness: 88,
      storyStrength: 48,
      leadSiphonPower: 58,
      ownerAnchorPower: 62,
    },
    {
      id: 'same-company-focus',
      titlePrefix: '同公司重点盘',
      segment: '内部重点',
      sourceBias: 'same_company',
      baseHeat: 60,
      freshness: 74,
      storyStrength: 58,
      leadSiphonPower: 50,
      ownerAnchorPower: 42,
    },
    {
      id: 'premium-story',
      titlePrefix: '强卖点竞品',
      segment: '卖点强',
      sourceBias: 'mixed',
      baseHeat: 64,
      freshness: 78,
      storyStrength: 72,
      leadSiphonPower: 54,
      ownerAnchorPower: 50,
    },
  ],
  signalTemplates: [
    {
      id: 'buyer-demand-rise',
      type: 'buyer_demand',
      title: '需求风声',
      message: '最近有一类买家在这个板块重新活跃，但真实预算还需要确认。',
    },
    {
      id: 'seller-comparing-stores',
      type: 'seller_intent',
      title: '业主比较门店',
      message: '听说有业主正在比较几家门店，可能会有新盘流入，也可能被别人先接走。',
    },
    {
      id: 'rival-activity-rise',
      type: 'rival_activity',
      title: '竞品动作变密',
      message: '附近门店这两天动作变密，同类房的参考价可能又被往下压了。',
    },
  ],
  dailyEventTemplates: [
    {
      id: 'shadow-rival-inflow',
      title: '新竞品入场',
      message: '商圈里突然多出一套同价位平替盘，客户注意力开始被分流。',
      tone: 'danger',
      layer: 'rival',
      effectType: 'rival_listing_inflow',
    },
    {
      id: 'shadow-customer-return',
      title: '客户回流',
      message: '有一位原本在别家看盘的客户回头来问你，适合判断是否值得接。',
      tone: 'success',
      layer: 'market',
      effectType: 'customer_return',
    },
    {
      id: 'shadow-company-squeeze',
      title: '公司资源变紧',
      message: '同公司内部也在抢共享客户和曝光位，今天资源位明显更紧。',
      tone: 'danger',
      layer: 'company',
      effectType: 'company_pressure_shift',
    },
    {
      id: 'shadow-seller-referral',
      title: '新业主找上门',
      message: '有业主通过熟人关系找到你，想让你评估一套新盘是否值得接。',
      tone: 'success',
      layer: 'seller',
      effectType: 'listing_inbound',
    },
    {
      id: 'shadow-demand-signal',
      title: '商圈风向变化',
      message: '板块里出现一条模糊需求信号，还不能直接当线索，但值得留意。',
      tone: 'accent',
      layer: 'market',
      effectType: 'signal_only',
    },
  ],
};

export function getBuiltInWorld() {
  return structuredClone(BUILT_IN_WORLD);
}
