import type { WorldSpec } from '../models.js';
import type {
  ChannelProfile,
  CustomerProfile,
  OwnerArchetype,
  RivalStoreArchetype,
  RivalListingArchetype,
} from '../../core/business-rules/archetypes/archetypeTaxonomy.js';
import {
  OWNER_ARCHETYPE_SEEDS,
  CUSTOMER_ARCHETYPE_SEEDS,
  CHANNEL_ARCHETYPE_SEEDS,
  RIVAL_STORE_ARCHETYPE_SEEDS,
  RIVAL_LISTING_ARCHETYPE_SEEDS,
} from '../../core/business-rules/archetypes/archetypeSeeds.js';

function mutableClone<T>(source: readonly T[]): T[] {
  return structuredClone([...source]) as T[];
}

export const BUILT_IN_WORLD: WorldSpec = {
  id: 'shanghai-resale-2026',
  version: 1,
  name: '上海二手房经营世界',
  marketCells: [
    {
      id: 'mc-qiantan',
      name: '浦东前滩 | 80-90㎡ 刚改',
      demandHeat: 76,
      supplyPressure: 62,
      competitivePressure: 58,
      sentiment: 68,
      monthlyFactors: [-8, -5, 2, 5, 6, 4, 1, -2, 7, 9, 3, -4],
    },
    {
      id: 'mc-jingan',
      name: '静安寺北 | 60-75㎡ 资产型',
      demandHeat: 81,
      supplyPressure: 54,
      competitivePressure: 51,
      sentiment: 71,
      monthlyFactors: [-6, -4, 3, 4, 5, 2, 1, -1, 6, 8, 2, -3],
    },
    {
      id: 'mc-xuhui',
      name: '徐汇滨江 | 85-110㎡ 品质改善',
      demandHeat: 72,
      supplyPressure: 58,
      competitivePressure: 49,
      sentiment: 66,
      monthlyFactors: [-7, -3, 2, 4, 7, 3, 0, -2, 5, 7, 1, -5],
    },
  ],
  channels: mutableClone<ChannelProfile>(CHANNEL_ARCHETYPE_SEEDS),
  customers: mutableClone<CustomerProfile>(CUSTOMER_ARCHETYPE_SEEDS),
  ownerArchetypes: mutableClone<OwnerArchetype>(OWNER_ARCHETYPE_SEEDS),
  housePrototypes: [
    {
      id: 'proto-ruiheli-89',
      title: '瑞和里 89㎡ 两房',
      community: '瑞和里',
      district: '浦东前滩',
      layout: '2室2厅1卫',
      area: 89,
      marketCellId: 'mc-qiantan',
      marketPrice: 802,
      bottomPrice: 785,
      story: '高确定性学区刚改叙事',
      tags: ['学区', '地铁近', '采光好'],
      defects: ['报价偏硬', '次卧偏小'],
      axisScores: { layout: 70, light: 85, floor: 60, decor: 50, amenity: 65, neighborhood: 80, structure: 75 },
    },
    {
      id: 'proto-xinghuyuan-92',
      title: '星湖苑 92㎡ 两房',
      community: '星湖苑',
      district: '浦东前滩',
      layout: '2室2厅1卫',
      area: 92,
      marketCellId: 'mc-qiantan',
      marketPrice: 836,
      bottomPrice: 808,
      story: '改善家庭稳定交付感',
      tags: ['改善', '车位', '采光好'],
      defects: ['总价高'],
      axisScores: { layout: 76, light: 80, floor: 73, decor: 64, amenity: 78, neighborhood: 84, structure: 77 },
    },
    {
      id: 'proto-jiangyuefu-128',
      title: '江悦府 128㎡ 三房',
      community: '江悦府',
      district: '浦东前滩',
      layout: '3室2厅2卫',
      area: 128,
      marketCellId: 'mc-qiantan',
      marketPrice: 1260,
      bottomPrice: 1208,
      story: '改善家庭稳定交付感',
      tags: ['改善', '江景', '车位'],
      defects: ['总价高', '竞品新'],
      axisScores: { layout: 82, light: 79, floor: 71, decor: 68, amenity: 83, neighborhood: 88, structure: 80 },
    },
    {
      id: 'proto-jiayue-71',
      title: '嘉樾公馆 71㎡ 一房',
      community: '嘉樾公馆',
      district: '静安寺北',
      layout: '1室1厅1卫',
      area: 71,
      marketCellId: 'mc-jingan',
      marketPrice: 645,
      bottomPrice: 590,
      story: '青年资产保值叙事',
      tags: ['总价友好', '地段强', '出租回报'],
      defects: ['朝向一般'],
      axisScores: { layout: 65, light: 50, floor: 90, decor: 85, amenity: 75, neighborhood: 95, structure: 60 },
    },
    {
      id: 'proto-jiali-east-118',
      title: '嘉里东院 118㎡ 三房',
      community: '嘉里东院',
      district: '静安寺北',
      layout: '3室2厅2卫',
      area: 118,
      marketCellId: 'mc-jingan',
      marketPrice: 1106,
      bottomPrice: 1048,
      story: '核心地段改善保值叙事',
      tags: ['地段强', '改善', '车位'],
      defects: ['得房率低'],
      axisScores: { layout: 78, light: 72, floor: 84, decor: 76, amenity: 88, neighborhood: 96, structure: 68 },
    },
    {
      id: 'proto-wanhang-63',
      title: '万航小区 63㎡ 一房',
      community: '万航小区',
      district: '静安寺北',
      layout: '1室1厅1卫',
      area: 63,
      marketCellId: 'mc-jingan',
      marketPrice: 598,
      bottomPrice: 562,
      story: '地段强总价友好叙事',
      tags: ['总价友好', '地段强'],
      defects: ['邻近马路'],
      axisScores: { layout: 61, light: 58, floor: 66, decor: 54, amenity: 71, neighborhood: 90, structure: 62 },
    },
    {
      id: 'proto-xuhui-95',
      title: '徐汇悦府 95㎡ 两房',
      community: '徐汇悦府',
      district: '徐汇滨江',
      layout: '2室2厅1卫',
      area: 95,
      marketCellId: 'mc-xuhui',
      marketPrice: 920,
      bottomPrice: 870,
      story: '品质改善叙事，靠近滨江绿道',
      tags: ['品质改善', '滨江', '采光好'],
      defects: ['挂牌偏高', '周边配套待成熟'],
      axisScores: { layout: 78, light: 82, floor: 72, decor: 70, amenity: 76, neighborhood: 74, structure: 76 },
    },
  ],
  randomEventTemplates: [
    { id: 'policy-shift', title: '政策利空', tone: 'danger', actor: '宏观' },
    { id: 'school-boom', title: '学区利好', tone: 'success', actor: '市场' },
    { id: 'competitor-cut', title: '竞对降价', tone: 'danger', actor: '市场竞争' },
  ],
  rivalStoreArchetypes: mutableClone<RivalStoreArchetype>(RIVAL_STORE_ARCHETYPE_SEEDS),
  rivalListingArchetypes: mutableClone<RivalListingArchetype>(RIVAL_LISTING_ARCHETYPE_SEEDS),
  signalTemplates: [
    {
      id: 'buyer-demand-rise',
      type: 'buyer_demand',
      title: '需求风声',
      message: '最近有一类买家在这个板块重新活跃，但真实预算还需要确认。',
    },
    {
      id: 'seller-comparing-stores',
      type: 'seller_intent',
      title: '业主比较门店',
      message: '听说有业主正在比较几家门店，可能会有新盘流入，也可能被别人先接走。',
    },
    {
      id: 'rival-activity-rise',
      type: 'rival_activity',
      title: '同类房有动静',
      message: '附近门店这两天动作变密，同类房的参考价可能又被往下压了。',
    },
  ],
  dailyEventTemplates: [
    {
      id: 'shadow-rival-inflow',
      title: '新同类房入场',
      message: '商圈里突然多出一套同价位平替盘，客户注意力开始被分流。',
      tone: 'danger',
      layer: 'rival',
      effectType: 'rival_listing_inflow',
    },
    {
      id: 'shadow-customer-return',
      title: '客户回流',
      message: '有一位原本在别家看盘的客户回头来问你，适合判断是否值得接。',
      tone: 'success',
      layer: 'market',
      effectType: 'customer_return',
    },
    {
      id: 'shadow-company-squeeze',
      title: '公司资源变紧',
      message: '同公司内部也在抢共享客户和曝光位，今天资源位明显更紧。',
      tone: 'danger',
      layer: 'company',
      effectType: 'company_pressure_shift',
    },
    {
      id: 'shadow-seller-referral',
      title: '新业主找上门',
      message: '有业主通过熟人关系找到你，想让你评估一套新盘是否值得接。',
      tone: 'success',
      layer: 'seller',
      effectType: 'listing_inbound',
    },
    {
      id: 'shadow-demand-signal',
      title: '商圈风向变化',
      message: '板块里出现一条模糊需求信号，还不能直接当线索，但值得留意。',
      tone: 'accent',
      layer: 'market',
      effectType: 'signal_only',
    },
  ],
};

export function getBuiltInWorld() {
  return structuredClone(BUILT_IN_WORLD);
}
