import type { DifficultyId } from '../models.js';
import type { ScenarioBlueprint } from './types.js';

const SCENARIO_BLUEPRINTS: ScenarioBlueprint[] = [
  {
    id: 'warmup-clean-handoff',
    difficultyId: 'warmup',
    label: '平稳热身',
    summary: '用一组更顺手的房源把基本操作跑顺。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'district_clusters',
    eventArcId: 'relationship_recovery',
    caseRoleSlots: [
      {
        id: 'anchor-main',
        role: 'anchor',
        pricePosition: 'market',
        windowPressure: 'wide',
        trustBias: 'stable',
        heatBias: 'warm',
        urgencyBias: 'low',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'traffic-side',
        role: 'traffic',
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'hot',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-side',
        role: 'grind',
        pricePosition: 'market',
        windowPressure: 'wide',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
      },
    ],
    naming: {
      titlePool: ['热身起步局', '平稳开场局', '操作找手感'],
      themeFragments: ['把基本操作跑顺', '重在熟悉保盘和推进', '不急着把难点同时压上来'],
      descriptionFragments: ['先找操作手感', '整体推进压力更轻', '是一张更友好的标准局'],
    },
  },
  {
    id: 'easy-relationship-recovery',
    difficultyId: 'easy',
    label: '稳盘回温',
    summary: '先保关系，再把热度慢慢做起来。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'district_clusters',
    eventArcId: 'relationship_recovery',
    caseRoleSlots: [
      {
        id: 'anchor-main',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'traffic-main',
        role: 'traffic',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'hot',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-side',
        role: 'fragile',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-side',
        role: 'grind',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'market',
        windowPressure: 'wide',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
        mustJoinCompetitionGroup: true,
      },
    ],
    naming: {
      titlePool: ['回温起步局', '稳盘热身局', '关系回稳局'],
      themeFragments: ['先稳住关系', '把热度慢慢做出来', '别急着乱动价'],
      descriptionFragments: ['适合熟悉经营动作', '顺风反馈更正向', '适合第一次感受双区取舍'],
    },
  },
  {
    id: 'easy-open-day-burst',
    difficultyId: 'easy',
    label: '周末拉热',
    summary: '用开放日和带看把客户热度做起来。',
    weight: 2,
    focusMarketCellIds: ['mc-qiantan'],
    competitionTopology: 'district_clusters',
    eventArcId: 'weekend_burst',
    caseRoleSlots: [
      {
        id: 'traffic-qiantan',
        role: 'traffic',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'hot',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-jingan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-jingan',
        role: 'grind',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'market',
        windowPressure: 'wide',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
        mustJoinCompetitionGroup: true,
      },
    ],
    naming: {
      titlePool: ['周末拉热局', '开放日冲带看', '邀约升温局'],
      themeFragments: ['用开放日把热度推起来', '让带看接上客户跟进', '把来访做厚'],
      descriptionFragments: ['更强调活动和邀约手感', '适合练热度经营', '前半程机会更友好'],
    },
  },
  {
    id: 'standard-double-market-balance',
    difficultyId: 'standard',
    label: '双区平衡',
    summary: '两个商圈都值得投入，但不能两边都贪。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'district_clusters',
    eventArcId: 'double_market_balance',
    caseRoleSlots: [
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-qiantan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-jingan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'traffic-jingan',
        role: 'traffic',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'hot',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-flex',
        role: 'grind',
        pricePosition: 'market',
        windowPressure: 'wide',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
      },
    ],
    naming: {
      titlePool: ['双区拉扯局', '两端平衡局', '资源分配局'],
      themeFragments: ['两边都有盘值得投', '先后顺序比单点动作更重要', '别让一头起火拖垮另一头'],
      descriptionFragments: ['更考验资源排序', '同类房源会明显互相影响', '需要兼顾关系和价格解释'],
    },
  },
  {
    id: 'standard-cross-pressure',
    difficultyId: 'standard',
    label: '交叉承压',
    summary: '市场机会和关系风险会交替出现。',
    weight: 2,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'paired_pressure',
    eventArcId: 'cross_pressure',
    caseRoleSlots: [
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-qiantan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-jingan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'traffic-jingan',
        role: 'traffic',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'hot',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-flex',
        role: 'grind',
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
      },
    ],
    naming: {
      titlePool: ['交叉承压局', '前后手博弈局', '取舍对冲局'],
      themeFragments: ['机会和风险会轮着来', '你得在推进和止损之间切换', '别被一波消息带偏判断'],
      descriptionFragments: ['中后程更考验取舍', '适合练承压决策', '每次误判都会放大成本'],
    },
  },
  {
    id: 'advanced-window-crossfire',
    difficultyId: 'advanced',
    label: '进阶承压',
    summary: '推进压力和竞争同时变快，要求更早做判断。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'paired_pressure',
    eventArcId: 'cross_pressure',
    caseRoleSlots: [
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-qiantan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-jingan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'traffic-jingan',
        role: 'traffic',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'hot',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-flex',
        role: 'grind',
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
      },
    ],
    naming: {
      titlePool: ['进阶承压局', '推进交火局', '前后手选择局'],
      themeFragments: ['推进压力和竞争会同时催你做判断', '错误动作会更快外溢', '开始要求主动做主次取舍'],
      descriptionFragments: ['比标准局更紧一点', '适合从会做过渡到会排优先级', '更考验判断速度'],
    },
  },
  {
    id: 'hard-window-squeeze',
    difficultyId: 'hard',
    label: '推进收紧',
    summary: '推进吃紧的盘更多，必须更快排主次。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'district_clusters',
    eventArcId: 'window_squeeze',
    caseRoleSlots: [
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-qiantan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-qiantan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-jingan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'hot',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'traffic-jingan',
        role: 'traffic',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-jingan',
        role: 'grind',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'below',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
        mustJoinCompetitionGroup: true,
      },
    ],
    naming: {
      titlePool: ['推进赛跑局', '主次分明局', '先救谁局'],
      themeFragments: ['推进很紧，要更早排主次', '不是每套盘都值得同样投入', '先手比补救更重要'],
      descriptionFragments: ['关键节点来得更密', '更考验先后顺序', '适合练高压优先级'],
    },
  },
  {
    id: 'extreme-last-stand',
    difficultyId: 'extreme',
    label: '残局识别',
    summary: '高噪声、高耦合、低容错，重在识别而不是全收。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'chain_clusters',
    eventArcId: 'competition_collapse',
    caseRoleSlots: [
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-qiantan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-qiantan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-jingan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'hot',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-jingan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'sacrifice-jingan',
        role: 'sacrifice',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'below',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'hot',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
    ],
    naming: {
      titlePool: ['极限残局局', '识别优先级局', '低容错结算局'],
      themeFragments: ['重点不是全盘通吃，而是识别谁该保', '高噪声里先判断再动作', '你需要接受一部分盘只能止损'],
      descriptionFragments: ['是更极端的标准局', '非常适合感受残局压力', '局面会更快逼你做决定'],
    },
  },
  {
    id: 'hard-competition-collapse',
    difficultyId: 'hard',
    label: '竞品踩踏',
    summary: '一套盘出问题，整组盘都会被带偏。',
    weight: 3,
    focusMarketCellIds: ['mc-qiantan', 'mc-jingan'],
    competitionTopology: 'chain_clusters',
    eventArcId: 'competition_collapse',
    caseRoleSlots: [
      {
        id: 'anchor-qiantan',
        role: 'anchor',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-qiantan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'grind-qiantan',
        role: 'grind',
        allowedMarketCellIds: ['mc-qiantan'],
        pricePosition: 'market',
        windowPressure: 'normal',
        trustBias: 'stable',
        heatBias: 'cold',
        urgencyBias: 'low',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'fragile-jingan',
        role: 'fragile',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'warm',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'spoiler-jingan',
        role: 'spoiler',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'premium',
        windowPressure: 'normal',
        trustBias: 'normal',
        heatBias: 'warm',
        urgencyBias: 'medium',
        mustJoinCompetitionGroup: true,
      },
      {
        id: 'sacrifice-jingan',
        role: 'sacrifice',
        allowedMarketCellIds: ['mc-jingan'],
        pricePosition: 'below',
        windowPressure: 'tight',
        trustBias: 'fragile',
        heatBias: 'hot',
        urgencyBias: 'high',
        mustJoinCompetitionGroup: true,
      },
    ],
    naming: {
      titlePool: ['链条坍塌局', '竞品踩踏局', '错位连锁局'],
      themeFragments: ['一套盘动作会带偏整组盘', '你需要主动控制连带影响', '别让竞品替你决定方向'],
      descriptionFragments: ['竞争耦合更强', '每次错误会更快传导', '适合练真正的资源排序'],
    },
  },
];

export function listScenarioBlueprints(difficultyId?: DifficultyId) {
  return SCENARIO_BLUEPRINTS
    .filter((blueprint) => !difficultyId || blueprint.difficultyId === difficultyId)
    .map((blueprint) => structuredClone(blueprint));
}

export function getScenarioBlueprintsForDifficulty(difficultyId: DifficultyId) {
  return listScenarioBlueprints(difficultyId);
}
