// ---------------------------------------------------------------------------
// bigWorldSpecFactory — default BigWorldSpec builder
//
// Creates a BigWorldSpec from a difficulty level and player case count.
// The spec is declarative; the actual world is generated by bigWorldBootstrap.ts.
// ---------------------------------------------------------------------------

import type {
  BigWorldSpec,
  BigWorldScalePolicy,
  BigWorldDomainConfig,
  BigWorldHiddenBoundary,
  BigWorldVisibleBoundary,
  BigWorldInvariants,
  BigWorldCaps,
} from './bigWorldTypes.js';
import type { DifficultyId } from '../models.js';

// ---------------------------------------------------------------------------
// Default scale policies per difficulty
// ---------------------------------------------------------------------------

function buildDefaultScalePolicy(
  difficultyId: DifficultyId,
  playerCaseCount: number,
): BigWorldScalePolicy {
  const scaleByDifficulty: Record<string, Partial<BigWorldScalePolicy>> = {
    warmup: {
      minMarketCells: 3,
      maxMarketCells: 3,
      namedBrokersPerAcn: 1,
      shadowBrokersPerAcn: 2,
      shadowListingsPerCell: 3,
      directRivalListingsPerCell: 2,
      materializedCustomersPerCell: 3,
      shadowAggregateClustersPerCell: 1,
      ownerProfilePriorCount: 3,
      customerCaseRatio: 8,
    },
    easy: {
      minMarketCells: 3,
      maxMarketCells: 4,
      namedBrokersPerAcn: 2,
      shadowBrokersPerAcn: 3,
      shadowListingsPerCell: 3,
      directRivalListingsPerCell: 1,
      materializedCustomersPerCell: 4,
      shadowAggregateClustersPerCell: 2,
      ownerProfilePriorCount: 4,
      customerCaseRatio: 10,
    },
    standard: {
      minMarketCells: 5,
      maxMarketCells: 7,
      acnCount: 3,
      namedBrokersPerAcn: 4,
      shadowBrokersPerAcn: 8,
      shadowListingsPerCell: 20,
      directRivalListingsPerCell: 5,
      materializedCustomersPerCell: 20,
      shadowAggregateClustersPerCell: 8,
      ownerProfilePriorCount: 100,
      customerCaseRatio: 10,
    },
    advanced: {
      minMarketCells: 4,
      maxMarketCells: 5,
      namedBrokersPerAcn: 2,
      shadowBrokersPerAcn: 5,
      shadowListingsPerCell: 5,
      directRivalListingsPerCell: 2,
      materializedCustomersPerCell: 5,
      shadowAggregateClustersPerCell: 3,
      ownerProfilePriorCount: 6,
      customerCaseRatio: 12,
    },
    hard: {
      minMarketCells: 4,
      maxMarketCells: 6,
      namedBrokersPerAcn: 3,
      shadowBrokersPerAcn: 6,
      shadowListingsPerCell: 6,
      directRivalListingsPerCell: 3,
      materializedCustomersPerCell: 6,
      shadowAggregateClustersPerCell: 3,
      ownerProfilePriorCount: 8,
      customerCaseRatio: 12,
    },
    extreme: {
      minMarketCells: 5,
      maxMarketCells: 6,
      namedBrokersPerAcn: 3,
      shadowBrokersPerAcn: 7,
      shadowListingsPerCell: 7,
      directRivalListingsPerCell: 3,
      materializedCustomersPerCell: 7,
      shadowAggregateClustersPerCell: 4,
      ownerProfilePriorCount: 10,
      customerCaseRatio: 14,
    },
    // ── hundred-scale: 大世界百量级初始化 ──
    // 100+ listings, 100+ owners, 300+ customers, 5+ cells, 3+ ACN, 20+ brokers
    // NOTE: market cell count is constrained by seededMarketWorld (3-5).
    //       We compensate with higher per-cell density.
    hundredScale: {
      minMarketCells: 5,
      maxMarketCells: 7,
      acnCount: 3,
      namedBrokersPerAcn: 4,
      shadowBrokersPerAcn: 8,
      shadowListingsPerCell: 20,
      directRivalListingsPerCell: 5,
      materializedCustomersPerCell: 20,
      shadowAggregateClustersPerCell: 8,
      ownerProfilePriorCount: 100,
      customerCaseRatio: 10,
    },
    // ── mega-scale: 几百量级业务世界 ──
    // 300+ listings, 300+ owners, 1000+ customers, 8+ cells, 5+ ACN, 60+ brokers
    // Each cell has micro cells and supporting info for source readiness.
    megaScale: {
      minMarketCells: 10,
      maxMarketCells: 12,
      acnCount: 5,
      namedBrokersPerAcn: 5,
      shadowBrokersPerAcn: 10,
      shadowListingsPerCell: 25,
      directRivalListingsPerCell: 7,
      materializedCustomersPerCell: 15,
      shadowAggregateClustersPerCell: 12,
      ownerProfilePriorCount: 300,
      customerCaseRatio: 10,
    },
    // ── super-market-scale: 市场级超大世界 ──
    // 真实市场规模：300+ listings, 300+ owners, 1000+ demand, 8+ cells, 5+ ACN, 60+ brokers
    // 24+ micro cells, 80+ supporting info, diverse owner/listing/broker/customer types
    // 反假大：每个实体必须有 source/causal/actor visibility 接入口
    superMarketScale: {
      minMarketCells: 10,
      maxMarketCells: 12,
      acnCount: 5,
      namedBrokersPerAcn: 5,
      shadowBrokersPerAcn: 10,
      shadowListingsPerCell: 30,
      directRivalListingsPerCell: 7,
      materializedCustomersPerCell: 20,
      shadowAggregateClustersPerCell: 15,
      ownerProfilePriorCount: 300,
      customerCaseRatio: 10,
    },
    // ── market-mega-scale: 真实市场规模世界 ──
    // Round 15: 500+ listings, 500+ owners, 3000+ demand, 100+ brokers, 20+ cells
    // 结构化市场：热区/冷区/成熟区/新兴区，高总价/刚需/改善/投资
    // 强竞品/弱竞品/垄断盘/分散盘，高意愿/犹豫/强硬/急售业主
    marketMegaScale: {
      minMarketCells: 20,
      maxMarketCells: 24,
      acnCount: 8,
      namedBrokersPerAcn: 5,
      shadowBrokersPerAcn: 15,
      shadowListingsPerCell: 25,
      directRivalListingsPerCell: 8,
      materializedCustomersPerCell: 25,
      shadowAggregateClustersPerCell: 20,
      ownerProfilePriorCount: 500,
      customerCaseRatio: 12,
    },
  };

  const overrides = scaleByDifficulty[difficultyId] ?? scaleByDifficulty.standard;

  return {
    minMarketCells: overrides.minMarketCells ?? 3,
    maxMarketCells: overrides.maxMarketCells ?? 5,
    acnCount: overrides.acnCount ?? 3,
    namedBrokersPerAcn: overrides.namedBrokersPerAcn ?? 2,
    shadowBrokersPerAcn: overrides.shadowBrokersPerAcn ?? 4,
    shadowListingsPerCell: overrides.shadowListingsPerCell ?? 4,
    directRivalListingsPerCell: overrides.directRivalListingsPerCell ?? 2,
    materializedCustomersPerCell: overrides.materializedCustomersPerCell ?? 5,
    shadowAggregateClustersPerCell: overrides.shadowAggregateClustersPerCell ?? 2,
    ownerProfilePriorCount: overrides.ownerProfilePriorCount ?? 5,
    customerCaseRatio: overrides.customerCaseRatio ?? 10,
  };
}

// ---------------------------------------------------------------------------
// Default domain config
// ---------------------------------------------------------------------------

function buildDefaultDomainConfig(): BigWorldDomainConfig {
  return {
    demandSegments: ['first_home', 'upgrade', 'school_district', 'investment', 'liquidity', 'commute', 'rental_yield'],
    priceBands: [
      { label: '150-250万', minPrice: 150, maxPrice: 250 },
      { label: '250-400万', minPrice: 250, maxPrice: 400 },
      { label: '400-600万', minPrice: 400, maxPrice: 600 },
      { label: '600-800万', minPrice: 600, maxPrice: 800 },
      { label: '800万以上', minPrice: 800, maxPrice: 1500 },
    ],
    brokerStyles: ['price_attacker', 'relationship_keeper', 'speed_runner', 'co_sale_builder', 'local_connector'],
    listingLayers: ['player', 'direct_rival', 'shadow', 'historical'],
  };
}

// ---------------------------------------------------------------------------
// Default boundaries
// ---------------------------------------------------------------------------

function buildDefaultHiddenBoundary(): BigWorldHiddenBoundary {
  return {
    maxInformationDelayDays: 5,
    maxOwnerPerceptionLagDays: 5,
    shadowSupplyVisible: false,
    shadowDemandVisible: false,
    rivalBrokerInternalsVisible: false,
  };
}

function buildDefaultVisibleBoundary(): BigWorldVisibleBoundary {
  return {
    playerListingsVisible: true,
    directRivalListingsVisible: true,
    namedRivalBrokersVisible: true,
    aggregateDemandVisible: true,
    recentWorldEventsVisible: true,
    cityCycleVisible: true,
  };
}

// ---------------------------------------------------------------------------
// Default invariants
// ---------------------------------------------------------------------------

function buildDefaultInvariants(): BigWorldInvariants {
  return {
    minMarketCells: 3,
    minRivalBrokers: 8,
    minComparableSupply: 20,
    minDemandUnits: 60,
    minOwnerProfilePriors: 3,
    minAcnNetworks: 3,
    deterministicReplay: true,
  };
}

// ---------------------------------------------------------------------------
// Default caps
// ---------------------------------------------------------------------------

function buildDefaultCaps(): BigWorldCaps {
  return {
    maxNamedBrokers: 50,
    maxMaterializedCustomers: 500,
    maxMaterializedListings: 500,
    maxRecentWorldEvents: 12,
  };
}

// ---------------------------------------------------------------------------
// Public: buildBigWorldSpec
// ---------------------------------------------------------------------------

/**
 * Build a BigWorldSpec from difficulty and player case count.
 * The spec is declarative and does not generate any entities.
 */
export function buildBigWorldSpec(
  difficultyId: DifficultyId,
  playerCaseCount: number,
): BigWorldSpec {
  return {
    version: 1,
    scale: buildDefaultScalePolicy(difficultyId, playerCaseCount),
    domain: buildDefaultDomainConfig(),
    hiddenBoundary: buildDefaultHiddenBoundary(),
    visibleBoundary: buildDefaultVisibleBoundary(),
    invariants: buildDefaultInvariants(),
    caps: buildDefaultCaps(),
  };
}
