export const BALANCE = {
  scoring: {
    competitivenessWeights: { d1: 0.5, d2: 0.25, d3: 0.25 },
    d1SignalWeights: {
      poolSize: 0.15,
      activeContacts: 0.2,
      lateStageThickness: 0.3,
      advanceSpeed: 0.2,
      stagnationRisk: 0.15,
    },
    d1Normalization: {
      poolSizeLogScale: 20,
      activeContactsLogScale: 20,
      lateStageBaseline: 5,
      lateStageScale: 40,
      advanceSpeedBaseline: 3,
      advanceSpeedScale: 30,
      stagnationPenaltyPerOpportunity: 10,
    },
    d2AxisWeights: {
      layout: 0.2,
      light: 0.1,
      floor: 0.1,
      decor: 0.15,
      amenity: 0.15,
      neighborhood: 0.2,
      structure: 0.1,
    },
    d3SignalWeights: {
      priceFlex: 0.25,
      patience: 0.25,
      urgency: 0.2,
      recentCooperation: 0.2,
      consistency: 0.1,
    },
    d3Normalization: {
      priceFlexFullScale: 10,
      consistencyBaseline: 80,
    },
    portalUrgencyWeights: {
      deltaWeight: 0.4,
      levelWeight: 0.2,
      criticalEventWeight: 0.25,
      timeWindowWeight: 0.15,
    },
    portalUrgencyNormalization: {
      deltaScale: 5,
      levelScale: 100,
      criticalEventScale: 100,
      timeWindowScale: 100,
    },
  },
  opportunities: {
    maxActivePerCase: 4,
    leadIntel: {
      recommendBrokerShadowChance: 0.35,
      brokerNetworkShadowChance: 0.2,
    },
    tick: {
      pricePenaltyDivisor: 9,
      intentHeatOffset: 55,
      intentHeatScale: 10,
      intentD1Offset: 50,
      intentD1Scale: 16,
      intentRandomMin: -4,
      intentRandomMax: 4,
      confidenceD3Offset: 50,
      confidenceD3Scale: 14,
      confidenceRandomMin: -3,
      confidenceRandomMax: 3,
      untouchedIntentLoss: 4,
      stageAdvanceIntentThreshold: 82,
      stageAdvanceChance: 0.35,
      stageAdvanceResetDaysLeft: 5,
      lossIntentThreshold: 32,
    },
    passiveLead: {
      heatDivisor: 240,
      d1Divisor: 600,
    },
    create: {
      rankedCandidateCount: 3,
      bonusStageThreshold: 14,
      boostedStageIndex: 1,
      boostedDaysLeft: 4,
      defaultDaysLeft: 5,
      pricePenaltyDivisor: 5,
      intentBase: 46,
      fitIntentWeight: 0.24,
      heatIntentWeight: 0.14,
      activityIntentWeight: 0.12,
      channelQualityWeight: 10,
      intentMin: 35,
      intentMax: 89,
      confidenceBase: 48,
      fitConfidenceWeight: 0.25,
      trustConfidenceWeight: 0.16,
      confidenceMin: 30,
      confidenceMax: 92,
    },
    fit: {
      layoutMatch: 18,
      layoutMismatch: 4,
      districtMatch: 18,
      districtMismatch: 0,
      budgetBase: 24,
      budgetDivisor: 10,
      budgetMin: 2,
      budgetMax: 24,
      preferenceIntersectionWeight: 6,
      competitivenessWeight: 0.16,
    },
  },
  actions: {
    negotiation: {
      strategies: {
        hold: { priceFactor: 1, shift: -6, loss: 14, wordOfMouthBonus: 0 },
        balanced: { priceFactor: 0.99, shift: 4, loss: 8, wordOfMouthBonus: 1 },
        close: { priceFactor: 0.985, shift: 9, loss: 5, wordOfMouthBonus: 2 },
      },
      intentWeight: 0.46,
      confidenceWeight: 0.24,
      urgentTrustWeight: 0.25,
      defaultTrustWeight: 0.18,
      competitivenessWeight: 0.16,
      askPricePenaltyWeight: 0.6,
      trustGate: 60,
      confidenceLossOnFailure: 8,
      failureDaysLeft: 2,
      lostIntentThreshold: 35,
      trustHit: {
        hold: { urgent: 1, pragmatic: 4, default: 3 },
        balanced: { urgent: 1, pragmatic: 3, default: 2 },
        close: { urgent: 0, emotional: 1, default: 2 },
      },
    },
    sale: {
      soldTrustBonus: 8,
      soldHeatBonus: 6,
      commissionRate: 0.01,
      advisorShareRate: 0.25,
      precisionFactor: 10,
      wordOfMouthBaseBonus: 4,
      losingOtherCustomersInterestPenalty: 24,
      losingOtherCustomersConfidencePenalty: 18,
      convertedStageIndex: 5,
    },
  },
  market: {
    marketPulse: {
      demandPulseScale: 3,
      demandRandomMin: -2,
      demandRandomMax: 2,
      supplyPulseScale: 2,
      supplyRandomMin: -2,
      supplyRandomMax: 2,
      pressureRandomMin: -2,
      pressureRandomMax: 3,
      sentimentSpreadWeight: 0.06,
      sentimentRandomMin: -2,
      sentimentRandomMax: 2,
      marketPriceSpreadDivisor: 18,
      marketPriceRandomMin: -3,
      marketPriceRandomMax: 3,
      marketPriceFloorRate: 0.84,
    },
    customerPulse: {
      activityWaveScale: 4,
      activityRandomMin: -3,
      activityRandomMax: 3,
      urgencyRandomMin: -2,
      urgencyRandomMax: 3,
    },
    caseTick: {
      untouchedHeatLossEmotionalBase: 4,
      untouchedHeatLossDefault: 2,
      pragmaticPriceGapLowPct: 3,
      pragmaticPriceGapHighPct: 5,
      pragmaticTightPriceTrustGain: 2,
      pragmaticWidePriceTrustLoss: 2,
      overpricedAskRate: 1.05,
      overpricedPragmaticTrustLoss: 3,
      overpricedElasticityBasePenalty: 1,
      overpricedHeatLoss: 2,
      overpricedPatienceLoss: 1,
      emotionalLowHeatThreshold: 40,
      emotionalLowHeatTrustLoss: 3,
      urgentGrowthFixed: 5,
      defaultUrgencyGrowthMin: 2,
      defaultUrgencyGrowthMax: 3,
      shortWindowThreshold: 6,
      shortWindowUrgencyBonus: 2,
      renewalTrustThreshold: 76,
      renewalD3Threshold: 62,
      renewalWindowDays: 4,
      renewalTrustLoss: 6,
    },
  },
  competition: {
    rivalLoss: {
      threatCooldownDays: 3,
      relationshipOpeningDays: 4,
      relationshipOpeningTrustThreshold: 58,
      trustCollapseThreshold: 36,
      coldHeatThreshold: 24,
      coldRelationshipDays: 3,
      pipelineHeatThreshold: 34,
      pipelinePressureThreshold: 16,
      pipelinePremiumThreshold: 0.075,
      pipelinePriceGapThreshold: 0.085,
      priceTrapPressureThreshold: 18,
      priceTrapPremiumThreshold: 0.085,
      priceTrapPriceGapThreshold: 0.09,
      priceTrapTrustThreshold: 48,
      priceTrapRelationshipDays: 3,
      priceTrapWindowDays: 2,
      recentlyMaintainedDays: 2,
      recentlyMaintainedTrustThreshold: 58,
      rivalOpenPressureThreshold: 14,
      rivalOpenPremiumThreshold: 0.065,
      rivalOpenPriceGapThreshold: 0.08,
      rawProbabilityBase: 0.03,
      rawPressureWeight: 0.008,
      rawPremiumOffset: 0.04,
      rawPremiumWeight: 1.8,
      rawPriceGapOffset: 0.055,
      rawPriceGapWeight: 1.5,
      rawBrokerLeadWeight: 0.035,
      lastWindowThreshold: 1,
      rawLastWindowBonus: 0.05,
      maintainedGuardWhenPipelineOpen: 0.6,
      probabilityMin: 0.005,
      probabilityMax: 0.18,
    },
    groupEffects: {
      premiumPenaltyWeight: 0.22,
      recentPriceCutterHeatLossWeight: 1.4,
      recentPriceCutterTrustLossWeight: 0.35,
      soldSpilloverHeatWeight: 6,
      soldSpilloverUrgencyWeight: 8,
    },
  },
} as const;
