import type { DifficultyOption } from '../models';

export const DIFFICULTY_OPTIONS: DifficultyOption[] = [
  {
    id: 'warmup',
    label: '热身局',
    summary: '3 套房，节奏最宽，适合先把手感找回来。',
    detail: '先把保盘、带看和节奏切换跑顺。这里更像轻松开场，不急着把你丢进复杂联动里。',
    scenarioCount: 1,
    featuredSeed: 1101,
    preview: [
      { label: '维护规模', value: '3 套，注意力宽松' },
      { label: '精力', value: '宽裕，容错高' },
      { label: '推广金', value: '够用，能试错' },
      { label: '房源状态', value: '整体平稳，少数偏冷' },
      { label: '业主意愿', value: '大多愿意配合' },
      { label: '竞争环境', value: '轻度联动' },
      { label: '市场环境', value: '整体友好' },
    ],
  },
  {
    id: 'easy',
    label: '入门局',
    summary: '4 套房，窗口更宽，顺风回合更多。',
    detail: '这一档更容易稳住业主，也更容易感受到月份和竞争联动，适合先摸清这游戏的基本节奏。',
    scenarioCount: 1,
    featuredSeed: 2202,
    preview: [
      { label: '维护规模', value: '4 套，刚好顺手' },
      { label: '精力', value: '比较够用' },
      { label: '推广金', value: '有空间做活动' },
      { label: '房源状态', value: '冷热开始分化' },
      { label: '业主意愿', value: '大体稳定' },
      { label: '竞争环境', value: '中低压力' },
      { label: '市场环境', value: '偏顺风' },
    ],
  },
  {
    id: 'standard',
    label: '标准局',
    summary: '5 套房，节奏平衡，需要兼顾关系、价格和线索。',
    detail: '这是默认档位。既要做选择，也要开始承担联动伤害。',
    scenarioCount: 1,
    featuredSeed: 3303,
    preview: [
      { label: '维护规模', value: '5 套，开始吃排序' },
      { label: '精力', value: '够用但要规划' },
      { label: '推广金', value: '要开始节制' },
      { label: '房源状态', value: '明显分层' },
      { label: '业主意愿', value: '有人开始摇摆' },
      { label: '竞争环境', value: '有可感知联动' },
      { label: '市场环境', value: '中性偏波动' },
    ],
  },
  {
    id: 'advanced',
    label: '进阶局',
    summary: '5 套房，但窗口更碎，关系和竞争会更快打架。',
    detail: '这一档开始更吃先后手。你需要主动决定哪些盘该保，哪些盘该先放一放。',
    scenarioCount: 1,
    featuredSeed: 4404,
    preview: [
      { label: '维护规模', value: '5 套，节奏更碎' },
      { label: '精力', value: '开始偏紧' },
      { label: '推广金', value: '每笔都要算' },
      { label: '房源状态', value: '更多错位盘' },
      { label: '业主意愿', value: '更容易波动' },
      { label: '竞争环境', value: '中高联动' },
      { label: '市场环境', value: '扰动变多' },
    ],
  },
  {
    id: 'hard',
    label: '高压局',
    summary: '6 套房，窗口更短，竞品和脚本压力更强。',
    detail: '错误动作会更快传导到整组竞争盘。想全救，通常就会全都顾不过来。',
    scenarioCount: 1,
    featuredSeed: 5505,
    preview: [
      { label: '维护规模', value: '6 套，高并发' },
      { label: '精力', value: '持续吃紧' },
      { label: '推广金', value: '偏少，不能乱花' },
      { label: '房源状态', value: '多盘窗口偏短' },
      { label: '业主意愿', value: '脆弱盘变多' },
      { label: '竞争环境', value: '强联动' },
      { label: '市场环境', value: '偏冷偏硬' },
    ],
  },
  {
    id: 'extreme',
    label: '极限局',
    summary: '6 套房，窗口和关系都更脆，适合专门练残局。',
    detail: '这档不要求你全盘通吃，而是要求你在高噪声里迅速识别谁该保、谁该放。',
    scenarioCount: 1,
    featuredSeed: 6606,
    preview: [
      { label: '维护规模', value: '6 套，几乎满负荷' },
      { label: '精力', value: '极限排班' },
      { label: '推广金', value: '非常紧，只能投重点' },
      { label: '房源状态', value: '多数盘先天吃亏' },
      { label: '业主意愿', value: '更易失去耐心' },
      { label: '竞争环境', value: '极强耦合' },
      { label: '市场环境', value: '多重利空' },
    ],
  },
];

export function getDifficultyOptions() {
  return structuredClone(DIFFICULTY_OPTIONS);
}
