export const STORAGE_KEY = "selling-world-save-v3";

export const CASE_STAGES = ["获客启动", "经营加热", "带看推进", "意向报价", "成交冲刺"];
export const OPPORTUNITY_STAGES = ["线索初识", "预约带看", "带看后追踪", "意向报价", "议价中"];

export const ACTIONS = [
  { id: "owner-call", name: "业主沟通", costEnergy: 1, costCash: 0, description: "先稳关系，再换窗口。适合信任偏低或窗口紧的盘。", type: "direct" },
  { id: "story", name: "精修卖点", costEnergy: 1, costCash: 0, description: "把房子的讲法修好，提升竞争力和带看转化。", type: "direct" },
  { id: "price-talk", name: "调价沟通", costEnergy: 1, costCash: 0, description: "在价格、速度和关系之间做真实取舍。", type: "scenario" },
  { id: "promote", name: "流量投放", costEnergy: 1, costCash: 2, description: "买来今天的曝光，快速补进线。", type: "direct" },
  { id: "open-day", name: "举办开放日", costEnergy: 2, costCash: 4, description: "集中拉热度，冷却 4 天，适合冲看房。", type: "direct" },
  { id: "showing", name: "安排带看", costEnergy: 1, costCash: 0, description: "把线索推进到看房后和报价前。", type: "direct" },
  { id: "negotiate", name: "议价冲刺", costEnergy: 1, costCash: 0, description: "对高阶段机会发起最后一推。", type: "scenario" },
];

export const CHANNELS = [
  { id: "search", name: "搜索流量", quality: 0.54, controllability: 0.4 },
  { id: "recommend", name: "推荐流量", quality: 0.66, controllability: 0.46 },
  { id: "open-day", name: "开放日", quality: 0.74, controllability: 0.76 },
  { id: "private", name: "私域转介", quality: 0.62, controllability: 0.69 },
];

export const MARKET_CELLS = [
  { id: "mc-qiantan", name: "浦东前滩 | 80-90㎡ 刚改", demandHeat: 76, supplyPressure: 62, competitivePressure: 58, sentiment: 68 },
  { id: "mc-xuhui", name: "徐汇滨江 | 120-130㎡ 改善", demandHeat: 64, supplyPressure: 48, competitivePressure: 72, sentiment: 63 },
  { id: "mc-jingan", name: "静安寺北 | 60-75㎡ 资产型", demandHeat: 81, supplyPressure: 54, competitivePressure: 51, sentiment: 71 },
  { id: "mc-minhang", name: "闵行古美 | 140-160㎡ 家庭改善", demandHeat: 53, supplyPressure: 70, competitivePressure: 66, sentiment: 57 },
];

export const INITIAL_CASES = [
  {
    id: "case-101",
    title: "瑞和里 89㎡ 两房",
    community: "瑞和里",
    district: "浦东前滩",
    layout: "2室2厅1卫",
    area: 89,
    askPrice: 828,
    marketPrice: 802,
    trust: 61,
    heat: 58,
    competitiveness: 64,
    urgency: 72,
    windowDays: 11,
    ownerName: "周女士",
    ownerMood: "担心拖久错过换房窗口",
    maintainerName: "林序",
    marketCellId: "mc-qiantan",
    story: "高确定性学区刚改叙事",
    tags: ["学区", "地铁近", "采光好"],
    defects: ["报价偏硬", "次卧偏小"],
  },
  {
    id: "case-102",
    title: "云栖苑 126㎡ 三房",
    community: "云栖苑",
    district: "徐汇滨江",
    layout: "3室2厅2卫",
    area: 126,
    askPrice: 1260,
    marketPrice: 1198,
    trust: 76,
    heat: 63,
    competitiveness: 57,
    urgency: 48,
    windowDays: 18,
    ownerName: "秦先生",
    ownerMood: "愿意等高净值客户，但不想被频繁打扰",
    maintainerName: "韩起",
    marketCellId: "mc-xuhui",
    story: "改善家庭稳定交付感",
    tags: ["江景", "改善", "车位"],
    defects: ["竞品新", "总价高"],
  },
  {
    id: "case-103",
    title: "嘉樾公馆 71㎡ 一房",
    community: "嘉樾公馆",
    district: "静安寺北",
    layout: "1室1厅1卫",
    area: 71,
    askPrice: 628,
    marketPrice: 645,
    trust: 54,
    heat: 67,
    competitiveness: 73,
    urgency: 85,
    windowDays: 7,
    ownerName: "梁先生",
    ownerMood: "希望尽快变现，耐心正在下降",
    maintainerName: "沈岚",
    marketCellId: "mc-jingan",
    story: "青年资产保值叙事",
    tags: ["总价友好", "地段强", "出租回报"],
    defects: ["朝向一般"],
  },
  {
    id: "case-104",
    title: "澜庭府 152㎡ 四房",
    community: "澜庭府",
    district: "闵行古美",
    layout: "4室2厅2卫",
    area: 152,
    askPrice: 1135,
    marketPrice: 1108,
    trust: 71,
    heat: 44,
    competitiveness: 52,
    urgency: 39,
    windowDays: 25,
    ownerName: "邵女士",
    ownerMood: "愿意试水，但希望经营更克制",
    maintainerName: "苏景",
    marketCellId: "mc-minhang",
    story: "改善置换生活半径升级",
    tags: ["四开间", "社区新", "学校稳"],
    defects: ["到店转化弱", "周边供应多"],
  },
];

export const CUSTOMER_POOL = [
  { id: "cus-01", name: "林家改善客", profile: "孩子今年入学，决策速度快", budgetMin: 780, budgetMax: 860, targetDistrict: "浦东前滩", layouts: ["2室2厅1卫", "3室2厅2卫"], activity: 82, urgency: 78, priceSensitivity: 68, preferences: ["地铁近", "学区", "采光好"] },
  { id: "cus-02", name: "陈先生新婚客", profile: "两个月内想落定婚房", budgetMin: 590, budgetMax: 660, targetDistrict: "静安寺北", layouts: ["1室1厅1卫", "2室2厅1卫"], activity: 79, urgency: 86, priceSensitivity: 72, preferences: ["地段强", "出租回报"] },
  { id: "cus-03", name: "赵女士置换客", profile: "看重交付确定性和车位", budgetMin: 1180, budgetMax: 1300, targetDistrict: "徐汇滨江", layouts: ["3室2厅2卫", "4室2厅2卫"], activity: 63, urgency: 58, priceSensitivity: 49, preferences: ["江景", "车位", "改善"] },
  { id: "cus-04", name: "孙先生学区客", profile: "对学区敏感，愿意多看几套", budgetMin: 760, budgetMax: 820, targetDistrict: "浦东前滩", layouts: ["2室2厅1卫"], activity: 56, urgency: 69, priceSensitivity: 74, preferences: ["学区", "采光好"] },
  { id: "cus-05", name: "方女士投资客", profile: "追求出租回报和总价控制", budgetMin: 610, budgetMax: 690, targetDistrict: "静安寺北", layouts: ["1室1厅1卫"], activity: 61, urgency: 52, priceSensitivity: 65, preferences: ["出租回报", "地段强"] },
  { id: "cus-06", name: "季先生改善客", profile: "预算谨慎，对教育配套敏感", budgetMin: 1080, budgetMax: 1160, targetDistrict: "闵行古美", layouts: ["4室2厅2卫"], activity: 45, urgency: 47, priceSensitivity: 70, preferences: ["四开间", "学校稳", "社区新"] },
  { id: "cus-07", name: "吴女士返沪家庭", profile: "愿意为稀缺景观付溢价", budgetMin: 1210, budgetMax: 1360, targetDistrict: "徐汇滨江", layouts: ["3室2厅2卫"], activity: 84, urgency: 82, priceSensitivity: 38, preferences: ["江景", "改善", "车位"] },
  { id: "cus-08", name: "蒋先生换房客", profile: "看重家庭生活动线", budgetMin: 1080, budgetMax: 1200, targetDistrict: "闵行古美", layouts: ["4室2厅2卫"], activity: 71, urgency: 61, priceSensitivity: 61, preferences: ["学校稳", "四开间"] },
  { id: "cus-09", name: "高女士首置客", profile: "需要更容易成交的两房盘", budgetMin: 780, budgetMax: 835, targetDistrict: "浦东前滩", layouts: ["2室2厅1卫"], activity: 76, urgency: 67, priceSensitivity: 78, preferences: ["地铁近", "采光好"] },
  { id: "cus-10", name: "许先生资产客", profile: "重视地段和转手效率", budgetMin: 600, budgetMax: 650, targetDistrict: "静安寺北", layouts: ["1室1厅1卫"], activity: 66, urgency: 73, priceSensitivity: 55, preferences: ["地段强", "总价友好"] },
];
